# Generated by Django 2.0.5 on 2018-05-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_visible',
        ),
    ]
