# Generated by Django 2.0.5 on 2018-05-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_email_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_visible',
            field=models.BooleanField(default=False),
        ),
    ]
