# Generated by Django 2.0.5 on 2018-05-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='create_time',
        ),
    ]
