"""
Django settings for twine_package_manager project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

from json import load


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRETS_DIR = os.path.join(BASE_DIR, 'secrets')

if not os.path.isdir(SECRETS_DIR):
    os.mkdir(SECRETS_DIR, 0o700)

SECRET_KEY = None
with open(os.path.join(SECRETS_DIR, 'django_secret_key')) as f:
    SECRET_KEY = f.read().strip()

POSTGRES_DATABASE_NAME = None
POSTGRES_DATABASE_PASSWORD = None
POSTGRES_DATABASE_USER = None
with open(os.path.join(SECRETS_DIR, 'postgres_db_credentials.json')) as f:
    data = load(f) 
    POSTGRES_DATABASE_NAME = data['databaseName']
    POSTGRES_DATABASE_PASSWORD = data['password']
    POSTGRES_DATABASE_USER = data['user']


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS must be specified to run outside of debug mode.
ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'account',
    'api',
    'home',
    'login',
    'logout',
    'packages',
    'profiles',
    'register',
    'versions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
]

LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'twine_package_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'templates/',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'twine_package_manager.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES_DATABASE_NAME,
        'USER': POSTGRES_DATABASE_USER,
        'PASSWORD': POSTGRES_DATABASE_PASSWORD,
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

_PREFIX = 'django.contrib.auth.password_validation.'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': '{}{}'.format(_PREFIX, 'UserAttributeSimilarityValidator'),
    },
    {
        'NAME': '{}{}'.format(_PREFIX, 'MinimumLengthValidator'),
    },
    {
        'NAME': '{}{}'.format(_PREFIX, 'CommonPasswordValidator'),
    },
    {
        'NAME': '{}{}'.format(_PREFIX, 'NumericPasswordValidator'),
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join('static'),)
