# Generated by Django 2.0.5 on 2018-08-19 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_identifier', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('js', models.TextField(blank=True, default='')),
                ('css', models.TextField(blank=True, default='')),
                ('homepage', models.URLField(blank=True, default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.Package')),
            ],
        ),
    ]
