# Generated by Django 2.1.3 on 2018-12-02 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semver_identifier', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('js', models.TextField(blank=True, default='')),
                ('css', models.TextField(blank=True, default='')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.Package')),
            ],
        ),
    ]
