# Generated by Django 2.1.3 on 2018-11-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='homepage',
        ),
    ]
