# Generated by Django 2.0.5 on 2018-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='version',
            name='js',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='version',
            name='version_identifier',
            field=models.TextField(blank=True, default=''),
        ),
    ]
