# Generated by Django 2.0.5 on 2018-11-14 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_default_version'),
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='parent_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.Package'),
        ),
    ]
