# Generated by Django 2.0.5 on 2018-11-14 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0002_version_parent_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
