# Generated by Django 2.0.5 on 2018-05-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0002_auto_20180524_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_identifier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
