# Generated by Django 2.0.5 on 2018-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0003_auto_20180524_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='name',
        ),
        migrations.AlterField(
            model_name='version',
            name='version_identifier',
            field=models.CharField(max_length=255),
        ),
    ]
