# Generated by Django 2.0.5 on 2018-11-15 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0003_auto_20181114_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='parent_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.Package'),
        ),
    ]
