# Generated by Django 2.0.5 on 2018-05-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20180524_0130'),
        ('versions', '0004_auto_20180524_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='parent_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.Package'),
        ),
    ]
