# Generated by Django 2.0.5 on 2018-05-24 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0005_version_parent_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='time_created',
            new_name='created_time',
        ),
    ]
