# Generated by Django 2.0.5 on 2018-05-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('accounts', '0001_initial'),
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='default_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='versions.Version'),
        ),
        migrations.AddField(
            model_name='package',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
    ]
