# Generated by Django 2.0.5 on 2018-11-14 07:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import packages.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_default_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date_modified',
            field=packages.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='package',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
        ),
    ]
