# Generated by Django 2.0.5 on 2018-05-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20180524_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
