# Generated by Django 2.0.5 on 2018-11-14 08:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20181114_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), blank=True, default=list, size=None),
        ),
    ]
