# Generated by Django 2.0.5 on 2018-11-15 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20181114_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDownloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_downloaded', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='deletedpackage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='downloads',
        ),
        migrations.AddField(
            model_name='deletedpackage',
            name='date_deleted',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='packagedownloads',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package'),
        ),
    ]
