# Generated by Django 2.0.5 on 2018-11-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20181115_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageDownloads',
            new_name='PackageDownload',
        ),
    ]
