# Generated by Django 2.1.3 on 2018-11-23 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20181115_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='default_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='versions.Version'),
        ),
    ]
