# Generated by Django 2.1.3 on 2018-11-23 03:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20181122_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, max_length=12, size=None),
        ),
    ]
