# Generated by Django 2.0.5 on 2018-05-24 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20180524_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
