# Generated by Django 2.0.5 on 2018-05-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_package_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='created_time',
            new_name='date_created',
        ),
    ]
