# Generated by Django 2.1.3 on 2018-11-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_auto_20181122_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
