# Generated by Django 2.0.5 on 2018-05-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_visible', models.BooleanField(default=False)),
                ('date_style', models.CharField(choices=[('DDMM', 'Day first'), ('MMDD', 'Month first')], default='MMDD', max_length=4)),
                ('time_style', models.CharField(choices=[('12H', 'Twelve hours'), ('24H', 'Twenty-four hours')], default='12H', max_length=3)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
